<?php

declare(strict_types=1);

namespace VitexSoftware\DigestModules\Tests\Core;

use PHPUnit\Framework\TestCase;
use VitexSoftware\DigestModules\Core\AbstractModule;
use VitexSoftware\DigestModules\Core\DataProviderInterface;

class ConcreteModule extends AbstractModule
{
    protected string $moduleName = 'test_module';
    protected string $heading = 'Test Module';
    protected string $description = 'A test module';

    public function process(DataProviderInterface $provider, \DatePeriod $period): array
    {
        return $this->createResult($period, true, ['key' => 'value']);
    }

    public function publicFormatCurrency(float $amount, string $currency = 'CZK'): array
    {
        return $this->formatCurrency($amount, $currency);
    }

    public function publicCalculatePercentage(float $value, float $total): float
    {
        return $this->calculatePercentage($value, $total);
    }

    public function publicCreateResult(\DatePeriod $period, bool $success, array $data = [], array $metadata = []): array
    {
        return $this->createResult($period, $success, $data, $metadata);
    }
}

class AbstractModuleTest extends TestCase
{
    private ConcreteModule $module;

    protected function setUp(): void
    {
        $this->module = new ConcreteModule();
    }

    public function testGetModuleName(): void
    {
        $this->assertSame('test_module', $this->module->getModuleName());
    }

    public function testGetModuleNameAutoGenerated(): void
    {
        $module = new ConcreteModule('', '', '');
        // Falls back to class-name-based generation when moduleName is set
        $this->assertSame('test_module', $module->getModuleName());
    }

    public function testGetHeading(): void
    {
        $this->assertSame('Test Module', $this->module->getHeading());
    }

    public function testGetDescription(): void
    {
        $this->assertSame('A test module', $this->module->getDescription());
    }

    public function testGetRequiredFeatures(): void
    {
        $this->assertSame([], $this->module->getRequiredFeatures());
    }

    public function testConstructorOverrides(): void
    {
        $module = new ConcreteModule('custom_name', 'Custom Heading', 'Custom Desc');
        $this->assertSame('custom_name', $module->getModuleName());
        $this->assertSame('Custom Heading', $module->getHeading());
        $this->assertSame('Custom Desc', $module->getDescription());
    }

    public function testFormatCurrency(): void
    {
        $result = $this->module->publicFormatCurrency(1234.56, 'CZK');
        $this->assertSame(1234.56, $result['amount']);
        $this->assertSame('CZK', $result['currency']);
        $this->assertStringContainsString('CZK', $result['formatted']);
    }

    public function testFormatCurrencyEur(): void
    {
        $result = $this->module->publicFormatCurrency(99.90, 'EUR');
        $this->assertSame('EUR', $result['currency']);
    }

    public function testCalculatePercentage(): void
    {
        $this->assertSame(50.0, $this->module->publicCalculatePercentage(50.0, 100.0));
        $this->assertSame(33.33, $this->module->publicCalculatePercentage(1.0, 3.0));
    }

    public function testCalculatePercentageZeroTotal(): void
    {
        $this->assertSame(0.0, $this->module->publicCalculatePercentage(10.0, 0.0));
    }

    public function testCreateResult(): void
    {
        $start = new \DateTime('2024-01-01');
        $end = new \DateTime('2024-02-01');
        $period = new \DatePeriod($start, new \DateInterval('P1D'), $end);

        $result = $this->module->publicCreateResult($period, true, ['foo' => 'bar']);

        $this->assertSame('test_module', $result['module_name']);
        $this->assertSame('Test Module', $result['heading']);
        $this->assertTrue($result['success']);
        $this->assertSame(['foo' => 'bar'], $result['data']);
        $this->assertSame('2024-01-01', $result['period']['start']);
        $this->assertSame('2024-02-01', $result['period']['end']);
        $this->assertArrayHasKey('timestamp', $result['metadata']);
    }

    public function testCreateResultFailure(): void
    {
        $start = new \DateTime('2024-01-01');
        $end = new \DateTime('2024-02-01');
        $period = new \DatePeriod($start, new \DateInterval('P1D'), $end);

        $result = $this->module->publicCreateResult($period, false);

        $this->assertFalse($result['success']);
        $this->assertSame([], $result['data']);
    }
}
